# -*- coding: utf-8 -*-
"""tags.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Q1qmJsROxycYTzRypXAfGRSs1y6rZDr
"""

import re

def validating_tags(given_tags):
    tags_validation = re.compile(r'<\/?[a-z]+>')
    return tags_validation.search(tags_validation, given_tags)